# Generated by Django 4.0.1 on 2022-01-21 14:01

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avatar',
            field=models.ImageField(null=True, upload_to=app.models.get_filename),
        ),
    ]
